// src/app/core/icons/lucide-icon-data.ts
// Five-orites Scoop — Lucide icon geometry (generated, do not hand-edit)
//
// GENERATED by scripts/generate-lucide-icons.mjs. Icons are licensed under the
// ISC License, Copyright (c) for Lucide contributors — https://lucide.dev
//
// These are raw SVG node arrays ([tag, attributes]), copied verbatim from the
// Lucide icon set. They carry no framework coupling, which is the point: the
// official Angular wrappers are either built for Angular 22 (@lucide/angular,
// uses the 18.1+ `@let` block) or deprecated and NgModule-based
// (lucide-angular). Rendering this data in AppIconComponent works on Angular 17
// and will keep working on whatever version comes next.
//
// Each entry is `[tag, attrs]`, where tag is one of the SVG shape elements
// Lucide emits. Regenerate after adding an icon to APP_ICONS.

/** One SVG shape: element name plus its attributes. */
export type IconNode = [tag: string, attrs: Record<string, string>];

/**
 * Icon geometry, keyed by the app-level name used in `<app-icon name="…">`.
 *
 * `satisfies`, NOT a `Record<string, IconNode[]>` annotation, and this line is
 * load-bearing in a way that is easy to undo by accident.
 *
 * An explicit `Record<string, …>` annotation WIDENS this object to
 * `Record<string, IconNode[]>`, so `keyof typeof` below — which is what
 * `AppIcon` in app-icons.ts is built from — becomes plain `string`. Every
 * `<app-icon name="…">` in the app then type-checks against `string`, and the
 * promise in that file's comment that a typo becomes a compile error is false.
 *
 * It was not theoretical: `name="upload"` on the inventory CSV button was not one
 * of these keys, so it rendered an empty `<svg>` and the button lost its icon with
 * nothing reporting a problem. Regenerating this file used to silently restore the
 * broken annotation, which is why the fix lives HERE and not in the generated
 * output.
 *
 * `satisfies` keeps the literal key union while still checking every value is a
 * well-formed `IconNode[]`, so a name outside the vocabulary stops compiling.
 */
export const LUCIDE_ICON_DATA = {
  home: [
    [
      'path',
      {
        d: 'M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8',
      },
    ],
    [
      'path',
      {
        d: 'M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z',
      },
    ],
  ],
  'ice-cream': [
    [
      'path',
      {
        d: 'm7 11 4.08 10.35a1 1 0 0 0 1.84 0L17 11',
      },
    ],
    [
      'path',
      {
        d: 'M17 7A5 5 0 0 0 7 7',
      },
    ],
    [
      'path',
      {
        d: 'M17 7a2 2 0 0 1 0 4H7a2 2 0 0 1 0-4',
      },
    ],
  ],
  cart: [
    [
      'circle',
      {
        cx: '8',
        cy: '21',
        r: '1',
      },
    ],
    [
      'circle',
      {
        cx: '19',
        cy: '21',
        r: '1',
      },
    ],
    [
      'path',
      {
        d: 'M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12',
      },
    ],
  ],
  receipt: [
    [
      'path',
      {
        d: 'M12 17V7',
      },
    ],
    [
      'path',
      {
        d: 'M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8',
      },
    ],
    [
      'path',
      {
        d: 'M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z',
      },
    ],
  ],
  layers: [
    [
      'path',
      {
        d: 'M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z',
      },
    ],
    [
      'path',
      {
        d: 'M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12',
      },
    ],
    [
      'path',
      {
        d: 'M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17',
      },
    ],
  ],
  clipboard: [
    [
      'rect',
      {
        width: '8',
        height: '4',
        x: '8',
        y: '2',
        rx: '1',
        ry: '1',
      },
    ],
    [
      'path',
      {
        d: 'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
      },
    ],
    [
      'path',
      {
        d: 'M12 11h4',
      },
    ],
    [
      'path',
      {
        d: 'M12 16h4',
      },
    ],
    [
      'path',
      {
        d: 'M8 11h.01',
      },
    ],
    [
      'path',
      {
        d: 'M8 16h.01',
      },
    ],
  ],
  'clipboard-check': [
    [
      'rect',
      {
        width: '8',
        height: '4',
        x: '8',
        y: '2',
        rx: '1',
        ry: '1',
      },
    ],
    [
      'path',
      {
        d: 'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2',
      },
    ],
    [
      'path',
      {
        d: 'm9 14 2 2 4-4',
      },
    ],
  ],
  chart: [
    [
      'path',
      {
        d: 'M3 3v16a2 2 0 0 0 2 2h16',
      },
    ],
    [
      'path',
      {
        d: 'M18 17V9',
      },
    ],
    [
      'path',
      {
        d: 'M13 17V5',
      },
    ],
    [
      'path',
      {
        d: 'M8 17v-3',
      },
    ],
  ],
  info: [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M12 16v-4',
      },
    ],
    [
      'path',
      {
        d: 'M12 8h.01',
      },
    ],
  ],
  users: [
    [
      'path',
      {
        d: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2',
      },
    ],
    [
      'path',
      {
        d: 'M16 3.128a4 4 0 0 1 0 7.744',
      },
    ],
    [
      'path',
      {
        d: 'M22 21v-2a4 4 0 0 0-3-3.87',
      },
    ],
    [
      'circle',
      {
        cx: '9',
        cy: '7',
        r: '4',
      },
    ],
  ],
  user: [
    [
      'path',
      {
        d: 'M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2',
      },
    ],
    [
      'circle',
      {
        cx: '12',
        cy: '7',
        r: '4',
      },
    ],
  ],
  'user-cog': [
    [
      'path',
      {
        d: 'M10 15H6a4 4 0 0 0-4 4v2',
      },
    ],
    [
      'path',
      {
        d: 'm14.305 16.53.923-.382',
      },
    ],
    [
      'path',
      {
        d: 'm15.228 13.852-.923-.383',
      },
    ],
    [
      'path',
      {
        d: 'm16.852 12.228-.383-.923',
      },
    ],
    [
      'path',
      {
        d: 'm16.852 17.772-.383.924',
      },
    ],
    [
      'path',
      {
        d: 'm19.148 12.228.383-.923',
      },
    ],
    [
      'path',
      {
        d: 'm19.53 18.696-.382-.924',
      },
    ],
    [
      'path',
      {
        d: 'm20.772 13.852.924-.383',
      },
    ],
    [
      'path',
      {
        d: 'm20.772 16.148.924.383',
      },
    ],
    [
      'circle',
      {
        cx: '18',
        cy: '15',
        r: '3',
      },
    ],
    [
      'circle',
      {
        cx: '9',
        cy: '7',
        r: '4',
      },
    ],
  ],
  'log-out': [
    [
      'path',
      {
        d: 'm16 17 5-5-5-5',
      },
    ],
    [
      'path',
      {
        d: 'M21 12H9',
      },
    ],
    [
      'path',
      {
        d: 'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4',
      },
    ],
  ],
  menu: [
    [
      'path',
      {
        d: 'M4 5h16',
      },
    ],
    [
      'path',
      {
        d: 'M4 12h16',
      },
    ],
    [
      'path',
      {
        d: 'M4 19h16',
      },
    ],
  ],
  settings: [
    [
      'path',
      {
        d: 'M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915',
      },
    ],
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '3',
      },
    ],
  ],
  clock: [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M12 6v6l4 2',
      },
    ],
  ],
  'circle-check': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'm9 12 2 2 4-4',
      },
    ],
  ],
  'circle-check-big': [
    [
      'path',
      {
        d: 'M21.801 10A10 10 0 1 1 17 3.335',
      },
    ],
    [
      'path',
      {
        d: 'm9 11 3 3L22 4',
      },
    ],
  ],
  'circle-alert': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'line',
      {
        x1: '12',
        x2: '12',
        y1: '8',
        y2: '12',
      },
    ],
    [
      'line',
      {
        x1: '12',
        x2: '12.01',
        y1: '16',
        y2: '16',
      },
    ],
  ],
  'triangle-alert': [
    [
      'path',
      {
        d: 'm21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3',
      },
    ],
    [
      'path',
      {
        d: 'M12 9v4',
      },
    ],
    [
      'path',
      {
        d: 'M12 17h.01',
      },
    ],
  ],
  'circle-x': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'm15 9-6 6',
      },
    ],
    [
      'path',
      {
        d: 'm9 9 6 6',
      },
    ],
  ],
  bike: [
    [
      'circle',
      {
        cx: '18.5',
        cy: '17.5',
        r: '3.5',
      },
    ],
    [
      'circle',
      {
        cx: '5.5',
        cy: '17.5',
        r: '3.5',
      },
    ],
    [
      'circle',
      {
        cx: '15',
        cy: '5',
        r: '1',
      },
    ],
    [
      'path',
      {
        d: 'M12 17.5V14l-3-3 4-3 2 3h2',
      },
    ],
  ],
  check: [
    [
      'path',
      {
        d: 'M20 6 9 17l-5-5',
      },
    ],
  ],
  'check-check': [
    [
      'path',
      {
        d: 'M18 6 7 17l-5-5',
      },
    ],
    [
      'path',
      {
        d: 'm22 10-7.5 7.5L13 16',
      },
    ],
  ],
  'cloud-off': [
    [
      'path',
      {
        d: 'M10.94 5.274A7 7 0 0 1 15.71 10h1.79a4.5 4.5 0 0 1 4.222 6.057',
      },
    ],
    [
      'path',
      {
        d: 'M18.796 18.81A4.5 4.5 0 0 1 17.5 19H9A7 7 0 0 1 5.79 5.78',
      },
    ],
    [
      'path',
      {
        d: 'm2 2 20 20',
      },
    ],
  ],
  loader: [
    [
      'path',
      {
        d: 'M21 12a9 9 0 1 1-6.219-8.56',
      },
    ],
  ],
  'wifi-off': [
    [
      'path',
      {
        d: 'M12 20h.01',
      },
    ],
    [
      'path',
      {
        d: 'M8.5 16.429a5 5 0 0 1 7 0',
      },
    ],
    [
      'path',
      {
        d: 'M5 12.859a10 10 0 0 1 5.17-2.69',
      },
    ],
    [
      'path',
      {
        d: 'M19 12.859a10 10 0 0 0-2.007-1.523',
      },
    ],
    [
      'path',
      {
        d: 'M2 8.82a15 15 0 0 1 4.177-2.643',
      },
    ],
    [
      'path',
      {
        d: 'M22 8.82a15 15 0 0 0-11.288-3.764',
      },
    ],
    [
      'path',
      {
        d: 'm2 2 20 20',
      },
    ],
  ],
  plus: [
    [
      'path',
      {
        d: 'M5 12h14',
      },
    ],
    [
      'path',
      {
        d: 'M12 5v14',
      },
    ],
  ],
  minus: [
    [
      'path',
      {
        d: 'M5 12h14',
      },
    ],
  ],
  trash: [
    [
      'path',
      {
        d: 'M10 11v6',
      },
    ],
    [
      'path',
      {
        d: 'M14 11v6',
      },
    ],
    [
      'path',
      {
        d: 'M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6',
      },
    ],
    [
      'path',
      {
        d: 'M3 6h18',
      },
    ],
    [
      'path',
      {
        d: 'M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2',
      },
    ],
  ],
  pencil: [
    [
      'path',
      {
        d: 'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
      },
    ],
    [
      'path',
      {
        d: 'm15 5 4 4',
      },
    ],
  ],
  save: [
    [
      'path',
      {
        d: 'M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z',
      },
    ],
    [
      'path',
      {
        d: 'M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7',
      },
    ],
    [
      'path',
      {
        d: 'M7 3v4a1 1 0 0 0 1 1h7',
      },
    ],
  ],
  copy: [
    [
      'rect',
      {
        width: '14',
        height: '14',
        x: '8',
        y: '8',
        rx: '2',
        ry: '2',
      },
    ],
    [
      'path',
      {
        d: 'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
      },
    ],
  ],
  eye: [
    [
      'path',
      {
        d: 'M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0',
      },
    ],
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '3',
      },
    ],
  ],
  'eye-off': [
    [
      'path',
      {
        d: 'M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49',
      },
    ],
    [
      'path',
      {
        d: 'M14.084 14.158a3 3 0 0 1-4.242-4.242',
      },
    ],
    [
      'path',
      {
        d: 'M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143',
      },
    ],
    [
      'path',
      {
        d: 'm2 2 20 20',
      },
    ],
  ],
  lock: [
    [
      'rect',
      {
        width: '18',
        height: '11',
        x: '3',
        y: '11',
        rx: '2',
        ry: '2',
      },
    ],
    [
      'path',
      {
        d: 'M7 11V7a5 5 0 0 1 10 0v4',
      },
    ],
  ],
  mail: [
    [
      'path',
      {
        d: 'm22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7',
      },
    ],
    [
      'rect',
      {
        x: '2',
        y: '4',
        width: '20',
        height: '16',
        rx: '2',
      },
    ],
  ],
  bell: [
    [
      'path',
      {
        d: 'M10.268 21a2 2 0 0 0 3.464 0',
      },
    ],
    [
      'path',
      {
        d: 'M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326',
      },
    ],
  ],
  filter: [
    [
      'path',
      {
        d: 'M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z',
      },
    ],
  ],
  refresh: [
    [
      'path',
      {
        d: 'M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8',
      },
    ],
    [
      'path',
      {
        d: 'M21 3v5h-5',
      },
    ],
    [
      'path',
      {
        d: 'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16',
      },
    ],
    [
      'path',
      {
        d: 'M8 16H3v5',
      },
    ],
  ],
  'arrow-right': [
    [
      'path',
      {
        d: 'M5 12h14',
      },
    ],
    [
      'path',
      {
        d: 'm12 5 7 7-7 7',
      },
    ],
  ],
  'arrow-left': [
    [
      'path',
      {
        d: 'm12 19-7-7 7-7',
      },
    ],
    [
      'path',
      {
        d: 'M19 12H5',
      },
    ],
  ],
  'chevron-right': [
    [
      'path',
      {
        d: 'm9 18 6-6-6-6',
      },
    ],
  ],
  'chevron-down': [
    [
      'path',
      {
        d: 'm6 9 6 6 6-6',
      },
    ],
  ],
  x: [
    [
      'path',
      {
        d: 'M18 6 6 18',
      },
    ],
    [
      'path',
      {
        d: 'm6 6 12 12',
      },
    ],
  ],
  heart: [
    [
      'path',
      {
        d: 'M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5',
      },
    ],
  ],
  star: [
    [
      'path',
      {
        d: 'M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z',
      },
    ],
  ],
  'star-half': [
    [
      'path',
      {
        d: 'M12 18.338a2.1 2.1 0 0 0-.987.244L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.12 2.12 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.12 2.12 0 0 0 1.597-1.16l2.309-4.679A.53.53 0 0 1 12 2',
      },
    ],
  ],
  zap: [
    [
      'path',
      {
        d: 'M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z',
      },
    ],
  ],
  'shield-check': [
    [
      'path',
      {
        d: 'M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z',
      },
    ],
    [
      'path',
      {
        d: 'm9 12 2 2 4-4',
      },
    ],
  ],
  smartphone: [
    [
      'rect',
      {
        width: '14',
        height: '20',
        x: '5',
        y: '2',
        rx: '2',
        ry: '2',
      },
    ],
    [
      'path',
      {
        d: 'M12 18h.01',
      },
    ],
  ],
  banknote: [
    [
      'rect',
      {
        width: '20',
        height: '12',
        x: '2',
        y: '6',
        rx: '2',
      },
    ],
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '2',
      },
    ],
    [
      'path',
      {
        d: 'M6 12h.01M18 12h.01',
      },
    ],
  ],
  'trending-up': [
    [
      'path',
      {
        d: 'M16 7h6v6',
      },
    ],
    [
      'path',
      {
        d: 'm22 7-8.5 8.5-5-5L2 17',
      },
    ],
  ],
  code: [
    [
      'path',
      {
        d: 'm16 18 6-6-6-6',
      },
    ],
    [
      'path',
      {
        d: 'm8 6-6 6 6 6',
      },
    ],
  ],
  frown: [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M16 16s-1.5-2-4-2-4 2-4 2',
      },
    ],
    [
      'line',
      {
        x1: '9',
        x2: '9.01',
        y1: '9',
        y2: '9',
      },
    ],
    [
      'line',
      {
        x1: '15',
        x2: '15.01',
        y1: '9',
        y2: '9',
      },
    ],
  ],
  image: [
    [
      'rect',
      {
        width: '18',
        height: '18',
        x: '3',
        y: '3',
        rx: '2',
        ry: '2',
      },
    ],
    [
      'circle',
      {
        cx: '9',
        cy: '9',
        r: '2',
      },
    ],
    [
      'path',
      {
        d: 'm21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21',
      },
    ],
  ],
  camera: [
    [
      'path',
      {
        d: 'M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z',
      },
    ],
    [
      'circle',
      {
        cx: '12',
        cy: '13',
        r: '3',
      },
    ],
  ],
  package: [
    [
      'path',
      {
        d: 'M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z',
      },
    ],
    [
      'path',
      {
        d: 'M12 22V12',
      },
    ],
    [
      'polyline',
      {
        points: '3.29 7 12 12 20.71 7',
      },
    ],
    [
      'path',
      {
        d: 'm7.5 4.27 9 5.15',
      },
    ],
  ],
  store: [
    [
      'path',
      {
        d: 'M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5',
      },
    ],
    [
      'path',
      {
        d: 'M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244',
      },
    ],
    [
      'path',
      {
        d: 'M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05',
      },
    ],
  ],
  truck: [
    [
      'path',
      {
        d: 'M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2',
      },
    ],
    [
      'path',
      {
        d: 'M15 18H9',
      },
    ],
    [
      'path',
      {
        d: 'M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14',
      },
    ],
    [
      'circle',
      {
        cx: '17',
        cy: '18',
        r: '2',
      },
    ],
    [
      'circle',
      {
        cx: '7',
        cy: '18',
        r: '2',
      },
    ],
  ],
  sparkles: [
    [
      'path',
      {
        d: 'M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z',
      },
    ],
    [
      'path',
      {
        d: 'M20 2v4',
      },
    ],
    [
      'path',
      {
        d: 'M22 4h-4',
      },
    ],
    [
      'circle',
      {
        cx: '4',
        cy: '20',
        r: '2',
      },
    ],
  ],
  palette: [
    [
      'path',
      {
        d: 'M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z',
      },
    ],
    [
      'circle',
      {
        cx: '13.5',
        cy: '6.5',
        r: '.5',
        fill: 'currentColor',
      },
    ],
    [
      'circle',
      {
        cx: '17.5',
        cy: '10.5',
        r: '.5',
        fill: 'currentColor',
      },
    ],
    [
      'circle',
      {
        cx: '6.5',
        cy: '12.5',
        r: '.5',
        fill: 'currentColor',
      },
    ],
    [
      'circle',
      {
        cx: '8.5',
        cy: '7.5',
        r: '.5',
        fill: 'currentColor',
      },
    ],
  ],
  'map-pin': [
    [
      'path',
      {
        d: 'M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0',
      },
    ],
    [
      'circle',
      {
        cx: '12',
        cy: '10',
        r: '3',
      },
    ],
  ],
  navigation: [
    [
      'polygon',
      {
        points: '3 11 22 2 13 21 11 13 3 11',
      },
    ],
  ],
  map: [
    [
      'path',
      {
        d: 'M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z',
      },
    ],
    [
      'path',
      {
        d: 'M15 5.764v15',
      },
    ],
    [
      'path',
      {
        d: 'M9 3.236v15',
      },
    ],
  ],
  ticket: [
    [
      'path',
      {
        d: 'M2 9a3 3 0 1 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 1 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z',
      },
    ],
    [
      'path',
      {
        d: 'M9 9h.01',
      },
    ],
    [
      'path',
      {
        d: 'm15 9-6 6',
      },
    ],
    [
      'path',
      {
        d: 'M15 15h.01',
      },
    ],
  ],
  phone: [
    [
      'path',
      {
        d: 'M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384',
      },
    ],
  ],
  gift: [
    [
      'path',
      {
        d: 'M12 7v14',
      },
    ],
    [
      'path',
      {
        d: 'M20 11v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8',
      },
    ],
    [
      'path',
      {
        d: 'M7.5 7a1 1 0 0 1 0-5A4.8 8 0 0 1 12 7a4.8 8 0 0 1 4.5-5 1 1 0 0 1 0 5',
      },
    ],
    [
      'rect',
      {
        x: '3',
        y: '7',
        width: '18',
        height: '4',
        rx: '1',
      },
    ],
  ],
  wallet: [
    [
      'path',
      {
        d: 'M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1',
      },
    ],
    [
      'path',
      {
        d: 'M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4',
      },
    ],
  ],
  percent: [
    [
      'line',
      {
        x1: '19',
        x2: '5',
        y1: '5',
        y2: '19',
      },
    ],
    [
      'circle',
      {
        cx: '6.5',
        cy: '6.5',
        r: '2.5',
      },
    ],
    [
      'circle',
      {
        cx: '17.5',
        cy: '17.5',
        r: '2.5',
      },
    ],
  ],
  tag: [
    [
      'path',
      {
        d: 'M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z',
      },
    ],
    [
      'circle',
      {
        cx: '7.5',
        cy: '7.5',
        r: '.5',
        fill: 'currentColor',
      },
    ],
  ],
  'chart-pie': [
    [
      'path',
      {
        d: 'M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z',
      },
    ],
    [
      'path',
      {
        d: 'M21.21 15.89A10 10 0 1 1 8 2.83',
      },
    ],
  ],
  'chart-bar': [
    [
      'path',
      {
        d: 'M3 3v16a2 2 0 0 0 2 2h16',
      },
    ],
    [
      'path',
      {
        d: 'M7 16h8',
      },
    ],
    [
      'path',
      {
        d: 'M7 11h12',
      },
    ],
    [
      'path',
      {
        d: 'M7 6h3',
      },
    ],
  ],
  peso: [
    [
      'path',
      {
        d: 'M20 11H4',
      },
    ],
    [
      'path',
      {
        d: 'M20 7H4',
      },
    ],
    [
      'path',
      {
        d: 'M7 21V4a1 1 0 0 1 1-1h4a1 1 0 0 1 0 12H7',
      },
    ],
  ],
  'chevron-left': [
    [
      'path',
      {
        d: 'm15 18-6-6 6-6',
      },
    ],
  ],
  'chevrons-left': [
    [
      'path',
      {
        d: 'm11 17-5-5 5-5',
      },
    ],
    [
      'path',
      {
        d: 'm18 17-5-5 5-5',
      },
    ],
  ],
  'chevrons-right': [
    [
      'path',
      {
        d: 'm6 17 5-5-5-5',
      },
    ],
    [
      'path',
      {
        d: 'm13 17 5-5-5-5',
      },
    ],
  ],
  search: [
    [
      'path',
      {
        d: 'm21 21-4.34-4.34',
      },
    ],
    [
      'circle',
      {
        cx: '11',
        cy: '11',
        r: '8',
      },
    ],
  ],
  list: [
    [
      'path',
      {
        d: 'M3 5h.01',
      },
    ],
    [
      'path',
      {
        d: 'M3 12h.01',
      },
    ],
    [
      'path',
      {
        d: 'M3 19h.01',
      },
    ],
    [
      'path',
      {
        d: 'M8 5h13',
      },
    ],
    [
      'path',
      {
        d: 'M8 12h13',
      },
    ],
    [
      'path',
      {
        d: 'M8 19h13',
      },
    ],
  ],
  'chart-column': [
    [
      'path',
      {
        d: 'M3 3v16a2 2 0 0 0 2 2h16',
      },
    ],
    [
      'rect',
      {
        x: '15',
        y: '5',
        width: '4',
        height: '12',
        rx: '1',
      },
    ],
    [
      'rect',
      {
        x: '7',
        y: '8',
        width: '4',
        height: '9',
        rx: '1',
      },
    ],
  ],
  gauge: [
    [
      'path',
      {
        d: 'm12 14 4-4',
      },
    ],
    [
      'path',
      {
        d: 'M3.34 19a10 10 0 1 1 17.32 0',
      },
    ],
  ],
  download: [
    [
      'path',
      {
        d: 'M12 15V3',
      },
    ],
    [
      'path',
      {
        d: 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4',
      },
    ],
    [
      'path',
      {
        d: 'm7 10 5 5 5-5',
      },
    ],
  ],
  upload: [
    [
      'path',
      {
        d: 'M12 3v12',
      },
    ],
    [
      'path',
      {
        d: 'm17 8-5-5-5 5',
      },
    ],
    [
      'path',
      {
        d: 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4',
      },
    ],
  ],
  'external-link': [
    [
      'path',
      {
        d: 'M15 3h6v6',
      },
    ],
    [
      'path',
      {
        d: 'M10 14 21 3',
      },
    ],
    [
      'path',
      {
        d: 'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6',
      },
    ],
  ],
  'shopping-bag': [
    [
      'path',
      {
        d: 'M16 10a4 4 0 0 1-8 0',
      },
    ],
    [
      'path',
      {
        d: 'M3.103 6.034h17.794',
      },
    ],
    [
      'path',
      {
        d: 'M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z',
      },
    ],
  ],
  'image-plus': [
    [
      'path',
      {
        d: 'M16 5h6',
      },
    ],
    [
      'path',
      {
        d: 'M19 2v6',
      },
    ],
    [
      'path',
      {
        d: 'M21 11.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7.5',
      },
    ],
    [
      'path',
      {
        d: 'm21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21',
      },
    ],
    [
      'circle',
      {
        cx: '9',
        cy: '9',
        r: '2',
      },
    ],
  ],
  'square-pen': [
    [
      'path',
      {
        d: 'M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7',
      },
    ],
    [
      'path',
      {
        d: 'M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z',
      },
    ],
  ],
  'circle-minus': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M8 12h8',
      },
    ],
  ],
  'circle-plus': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M8 12h8',
      },
    ],
    [
      'path',
      {
        d: 'M12 8v8',
      },
    ],
  ],
  calendar: [
    [
      'path',
      {
        d: 'M8 2v4',
      },
    ],
    [
      'path',
      {
        d: 'M16 2v4',
      },
    ],
    [
      'rect',
      {
        width: '18',
        height: '18',
        x: '3',
        y: '4',
        rx: '2',
      },
    ],
    [
      'path',
      {
        d: 'M3 10h18',
      },
    ],
  ],
  'text-cursor-input': [
    [
      'path',
      {
        d: 'M12 20h-1a2 2 0 0 1-2-2 2 2 0 0 1-2 2H6',
      },
    ],
    [
      'path',
      {
        d: 'M13 8h7a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-7',
      },
    ],
    [
      'path',
      {
        d: 'M5 16H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h1',
      },
    ],
    [
      'path',
      {
        d: 'M6 4h1a2 2 0 0 1 2 2 2 2 0 0 1 2-2h1',
      },
    ],
    [
      'path',
      {
        d: 'M9 6v12',
      },
    ],
  ],
  'sliders-horizontal': [
    [
      'path',
      {
        d: 'M10 5H3',
      },
    ],
    [
      'path',
      {
        d: 'M12 19H3',
      },
    ],
    [
      'path',
      {
        d: 'M14 3v4',
      },
    ],
    [
      'path',
      {
        d: 'M16 17v4',
      },
    ],
    [
      'path',
      {
        d: 'M21 12h-9',
      },
    ],
    [
      'path',
      {
        d: 'M21 19h-5',
      },
    ],
    [
      'path',
      {
        d: 'M21 5h-7',
      },
    ],
    [
      'path',
      {
        d: 'M8 10v4',
      },
    ],
    [
      'path',
      {
        d: 'M8 12H3',
      },
    ],
  ],
  contrast: [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M12 18a6 6 0 0 0 0-12v12z',
      },
    ],
  ],
  'map-pinned': [
    [
      'path',
      {
        d: 'M18 8c0 3.613-3.869 7.429-5.393 8.795a1 1 0 0 1-1.214 0C9.87 15.429 6 11.613 6 8a6 6 0 0 1 12 0',
      },
    ],
    [
      'circle',
      {
        cx: '12',
        cy: '8',
        r: '2',
      },
    ],
    [
      'path',
      {
        d: 'M8.714 14h-3.71a1 1 0 0 0-.948.683l-2.004 6A1 1 0 0 0 3 22h18a1 1 0 0 0 .948-1.316l-2-6a1 1 0 0 0-.949-.684h-3.712',
      },
    ],
  ],
} satisfies Record<string, IconNode[]>;

export type LucideIconName = keyof typeof LUCIDE_ICON_DATA;
